doctrine:
    dbal:
        driver: pdo_pgsql
        dbname: '%env(resolve:DB_NAME)%'
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        server_version: '%env(DB_SERVER_VERSION)%'

        types:
            jsonb: MartinGeorgiev\Doctrine\DBAL\Types\Jsonb
            jsonb[]: MartinGeorgiev\Doctrine\DBAL\Types\JsonbArray

        mapping_types:
            jsonb: jsonb

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        dql:
            string_functions:
                JSONB_CONTAINS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Contains

        mappings:
            Shared:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Database/ORM'
                prefix: 'App\Users\Domain\Entity'
                alias: Users
            ProductionProcess:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/ProductionProcess/Infrastructure/Database/ORM'
                prefix: 'App\ProductionProcess\Domain\Aggregate'
                alias: ProductionProcess
            Orders:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Orders/Infrastructure/Database/ORM'
                prefix: 'App\Orders\Domain\Aggregate'
                alias: Orders
            Inventory:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Inventory/Infrastructure/Database/ORM'
                prefix: 'App\Inventory\Domain\Aggregate'
                alias: Inventory
when@test:
    doctrine:
        dbal:
            driver: 'pdo_sqlite'
            url: 'sqlite:///:memory:'
            memory: true
#        orm:
#            auto_generate_proxy_classes: true
#            metadata_cache_driver:
#                type: array
#            query_cache_driver: 'array'
#            result_cache_driver: 'array'


when@prod:
    doctrine:
        orm:
            metadata_cache_driver:
                type: pool
                pool: cache.metadata
            query_cache_driver:
                type: pool
                pool: cache.query
            result_cache_driver:
                type: pool
                pool: cache.result
