doctrine:
    dbal:
        driver: pdo_pgsql
        dbname: '%env(resolve:DB_NAME)%'
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Shared:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Database/ORM'
                prefix: 'App\Users\Domain\Entity'
                alias: Users
#            Orders:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%/src/Orders/Infrastructure/Database/ORM'
#                prefix: 'App\Orders\Domain\Aggregate'
#                alias: Orders
            Inventory:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Inventory/Infrastructure/Database/ORM'
                prefix: 'App\Inventory\Domain\Aggregate'
                alias: Inventory
#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

#when@prod:
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool

#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
