framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
                    #- App\Shared\Infrastructure\Middleware\ExceptionMiddleware
            query.bus:
            event.bus:
                default_middleware:
                    allow_no_handlers: true
                    enabled: true

        failure_transport: failed

        transports:
            production_process:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                    jitter: 0.1

                options:
                    exchange:
                        name: 'production_process'
                        type: 'topic'
                    queues:
                        production_process:
                            binding_keys:
                                - 'production_process.#'
                                - 'inventory.#'
            inventory:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                options:
                    exchange:
                        name: 'inventory'
                        type: 'topic'
                    queues:
                        inventory:
                            binding_keys:
                                - 'inventory.#'
            orders:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                options:
                    exchange:
                        name: 'orders'
                        type: 'topic'
                    queues:
                        orders:
                            binding_keys:
                                - 'production_process.#'
                                - 'orders.#'
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'dlx_exchange'
                    queues:
                        dlq_queue: ~
        routing:
            'App\ProductionProcess\Infrastructure\Event\EventEnvelope': [production_process, inventory]
            'App\Orders\Infrastructure\Event\EventEnvelope': [production_process, orders]
            'App\Inventory\Infrastructure\Event\EventEnvelope': [inventory, production_process]
