framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
                    - App\Shared\Infrastructure\Middleware\ExceptionMiddleware
            query.bus:
            event.bus:
                default_middleware:
                    allow_no_handlers: true
                    enabled: true

        transports:
            production_process:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\ProductionProcess\Infrastructure\Event\EventEnvelopeSerializer'
                options:
                    exchange:
                        name: 'production_process'
                        type: 'topic'
                    queues:
                        production_process:
                            binding_keys:
                                - 'production_process.#'
                                - 'inventory.#'
            inventory:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Inventory\Infrastructure\Event\EventEnvelopeSerializer'
                options:
                    exchange:
                        name: 'inventory'
                        type: 'topic'
                    queues:
                        inventory:
                            binding_keys:
                                - 'inventory.#'
            orders:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Orders\Infrastructure\Event\EventEnvelopeSerializer'
                options:
                    exchange:
                        name: 'orders'
                        type: 'topic'
                    queues:
                        orders:
                            binding_keys:
                                - 'production_process.#'
                                - 'orders.#'
        routing:
            'App\ProductionProcess\Infrastructure\Event\EventEnvelope': [production_process, inventory]
            'App\Orders\Infrastructure\Event\EventEnvelope': [production_process, orders]
            'App\Inventory\Infrastructure\Event\EventEnvelope': [inventory]
