framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
                    - App\Shared\Infrastructure\Middleware\ExceptionMiddleware
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers

        transports:
            orders:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Shared\Infrastructure\Event\EventEnvelopeSerializer'
                options:
                    exchange:
                        name: 'orders'
                        type: 'topic'
                    queues:
                        orders:
                            binding_keys:
                                - 'orders.#'
                                - 'payments.#'

        routing:
            'App\Orders\Infrastructure\Event\EventEnvelope': [orders]
