services:
  php-fpm-staging:
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/
    ports:
      - 8080
    networks:
      traefik-web:
    labels:
      - traefik.enable=true
      - traefik.http.routers.orderpilot-staging.entrypoints=web-secured,web
      - traefik.http.routers.orderpilot-staging.rule=Host(`staging.orderpilot.codality.co`)
      - traefik.http.routers.orderpilot-staging.tls=true
      - traefik.http.routers.orderpilot-staging.tls.certresolver=mytlschallenge
      - traefik.http.services.orderpilot-staging.loadbalancer.server.port=8080
      - traefik.http.routers.orderpilot-staging.middlewares=redirect-www-to-non-www@file

  postgres-staging:
    build:
      context: ./postgres
    hostname: postgres-staging
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_staging:/var/lib/postgresql/data:rw
    networks:
      traefik-web:

volumes:
  db_data_staging:

networks:
  traefik-web:
    external: true