global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'symphony_php_fpm'
    metrics_path: '/metrics/prometheus'  # Укажите путь к метрикам
    static_configs:
      - targets: ['php-fpm:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']