controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: attribute

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: attribute

api_refresh_token:
    path: /api/auth/refresh-token
    methods: POST

api_login_check:
    path: /api/auth/token
    methods: POST

users:
    resource: ../src/Users/Infrastructure/Controller/
    type: attribute

rolls:
    resource: ../src/Orders/Infrastructure/Controller/
    type: attribute

inventory:
    resource: ../src/Inventory/Infrastructure/Controller/
    type: attribute

prod-process:
    resource: ../src/ProductionProcess/Infrastructure/Controller/
    type: attribute