<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIJnpjh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIJnpjh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRIJnpjh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRIJnpjh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRIJnpjh\App_KernelDevDebugContainer([
    'container.build_hash' => 'RIJnpjh',
    'container.build_id' => '3f5438fc',
    'container.build_time' => 1720703329,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIJnpjh');
